2-UI
PPJ-PE/ProjetoIA pull request #3
Opened 2023-06-01 13:08 UTC by RyannThi

vai (alguem apagou esse pull request antes? eu juro que tinha feito mas fui olhar no historico e n tinha nada)

2023-06-02 21:11 UTC, ArthurPedroso commented on Assets/Images/Interface/In-Game/RadioBase.png
Nice Work!

2023-06-02 21:19 UTC, ArthurPedroso requested changes
Muito top, so colocar aqla funcao la q eu pedi pra dar pra controlar a UI que ja era. Obrigado pelo bom trabalho!

2023-06-02 21:19 UTC, ArthurPedroso commented on Assets/Scripts/Interface/GameOverScreen.cs
Hmmm esse Arquivo n tem mt a ver com a tarefa, sepa era melhor n ter comitado isso aqui

2023-06-02 21:19 UTC, ArthurPedroso commented on Assets/Scripts/Interface/GameOverScreen.cs
Favor deletar plz

2023-06-02 21:19 UTC, ArthurPedroso commented on Assets/Scripts/Interface/AlertMeter.cs
> +            currentState = AlertState.Normal;
Usar "GetChildGameObject" n eh mt legal aqui pq se algum dia alguem tiver que refazer esse prefab, vai ter que ver primeiro o codigo pra depois montar o objeto com a msm hierarquia que esse aqui. O idel eh usar [SerializeField] GameObject, e passar na mao na untiy

2023-06-02 21:19 UTC, ArthurPedroso commented on Assets/Scripts/Interface/AlertMeter.cs
> +            radioShadowCGroup = radioShadow.GetComponent<CanvasGroup>();
Tudo bem usar GetComponent no start, mas o melhor msm eh n usar. Depois o start do jogo fica meio pesado. Mas sem problemas, tem a vantagem de n ter mt coisa pra referenciaar

2023-06-02 21:19 UTC, ArthurPedroso commented on Assets/Scripts/Interface/AlertMeter.cs
> +        }
No geral, ficou bem legal esse script, so faltou um metodo publico que permita alguem controlar essa UI:
```suggestion
        }
        public void SetAlertLevel(float _alertLevel)
        {
            if (_alertLevel > 1.0f || _alertLevel < 0)
            {
                Debug.LogError("Invalid alert level!!!");
                return;
            }
            fillAmount = _alertLevel;
        }
```

2023-06-07 15:32 UTC, RyannThi commented on Assets/Scripts/Interface/AlertMeter.cs
> +        }
blz, agradeço já mandar kk

2023-06-07 15:33 UTC, RyannThi commented on Assets/Scripts/Interface/AlertMeter.cs
> +            radioShadowCGroup = radioShadow.GetComponent<CanvasGroup>();
agora que coloquei pra importar direto do inspetor, o tipo ja é definido logo de cara quando adiciono eles no script

2023-06-07 15:33 UTC, RyannThi commented on Assets/Scripts/Interface/AlertMeter.cs
> +            currentState = AlertState.Normal;
perfeito

2023-06-07 15:33 UTC, RyannThi commented on Assets/Scripts/Interface/GameOverScreen.cs
👍

2023-06-07 17:14 UTC, ArthurPedroso approved these changes
Muito bom!

2023-06-07 17:14 UTC, merged